# ============================================================
# Build stage: Java + Maven + WebFX CLI + TeaVM build
# ============================================================
FROM maven:3.9-eclipse-temurin-21 AS build

WORKDIR /app

# Git is needed to clone WebFX CLI
RUN apt-get update \
    && apt-get install -y --no-install-recommends git bash sed python3 \
    && rm -rf /var/lib/apt/lists/*

# Install WebFX CLI
WORKDIR /opt
RUN git clone https://github.com/webfx-project/webfx-cli.git \
    && cd webfx-cli \
    && mvn -q -DskipTests package

# The WebFX CLI fat jar is generated by the WebFX CLI build.
# This wrapper lets us call "webfx" from anywhere.
RUN printf '#!/usr/bin/env sh\njava -jar /opt/webfx-cli/target/webfx-cli-0.1.0-SNAPSHOT-fat.jar "$@"\n' > /usr/local/bin/webfx \
    && chmod +x /usr/local/bin/webfx

# Copy project
WORKDIR /app
COPY . .

# Regenerate WebFX files
RUN webfx update

# Patch module-info.java generated by WebFX:
# - WebFX may generate "requires teavm.jso;" but the real module is "org.teavm.jso"
# - WebFX may generate "opens sounds;" but sounds is a resource folder, not a Java package
RUN if [ -f pong/src/main/java/module-info.java ]; then \
      sed -i 's/requires teavm\.jso;/requires org.teavm.jso;/g' pong/src/main/java/module-info.java && \
      sed -i '/opens sounds;/d' pong/src/main/java/module-info.java ; \
    fi

# Build TeaVM JS target
RUN mvn clean package -Pteavm-js -pl pong-teavm-js -am

# Preserve the WebFX generated index as game.html
RUN cp pong-teavm-js/target/pong-teavm-js-1.0.0/index.html \
       pong-teavm-js/target/pong-teavm-js-1.0.0/game.html

# Inject CSS into game.html so the WebFX iframe has black background and no scrollbars
RUN python3 - <<'PY'
from pathlib import Path

game = Path("pong-teavm-js/target/pong-teavm-js-1.0.0/game.html")
html = game.read_text(encoding="utf-8")

patch = """
<style>
    html,
    body {
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background: #05070b !important;
    }

    body {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    canvas,
    svg {
        width: 900px;
        height: 600px;
        max-width: 100vw;
        max-height: 100vh;
        display: block;
    }
</style>
</head>
"""

html = html.replace("</head>", patch)
game.write_text(html, encoding="utf-8")
PY

# Replace index.html with custom landing page if present
RUN if [ -f custom-web/index.html ]; then \
      cp custom-web/index.html pong-teavm-js/target/pong-teavm-js-1.0.0/index.html ; \
    fi

# ============================================================
# Runtime stage: static files served by Nginx
# ============================================================
FROM nginx:1.27-alpine AS runtime

COPY --from=build /app/pong-teavm-js/target/pong-teavm-js-1.0.0 /usr/share/nginx/html

EXPOSE 80